architectural changes and addition of CPU throttling and power management

diff --git a/bin/corgi-audio-control b/bin/corgi-audio-control
--- a/bin/corgi-audio-control
+++ b/bin/corgi-audio-control
@@ -1,46 +1,42 @@
-corgiUpdateVolume() {
+#!/bin/sh
 
-  audioHandler=amixer
-  option="$1"
+# Copyright 2016 Antonio Malcolm, released under an MPL, v. 2.0, license. All rights reserved.
+#
+# This file is part of Corgi Scripts (also referred to as corgi-scripts).
+#
+# Corgi Scripts is subject to the terms of the Mozilla Public License, v. 2.0. 
+# If a copy of the MPL was not distributed with this file, 
+# you can obtain one at http://mozilla.org/MPL/2.0/.
+#
+# Corgi Scripts is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either expressed or implied.
+# See LICENSE.txt, for the specific language governing rights and limitations under the License,
+# which should have been provided with this software, or visit http://mozilla.org/MPL/2.0/.
 
-  case "$option" in
+# corgi-audio-management.shlib - handles management of audio features, such as volume and muting
+#
+# v2016.04.11
+#
+# Authored by Antonio Malcolm
+#
+# 
+# Requires: corgi-audio-management.shlib
 
-    'up') $audioHandler 'sset' 'Master' '5%+' ;;
-    'down') $audioHandler 'sset' 'Master' '5%-' ;;
 
-    'mute')
+currentDirectory="`dirname "$0"`"
+currentDirectory="`cd "$currentDirectory" ; pwd -P `"
+parentDirectory="`dirname $currentDirectory`"
 
-      $audioHandler 'sget' 'Master' | {
-      
-        muteDirective='unmute'
+corgiAudioManagementLib="$parentDirectory/lib/corgi/corgi-audio-management.shlib"
 
-        while read -r line
-        do
+if [ ! -e "$corgiAudioManagementLib" ]
+then
+  logger "ERROR (corgi-audio-control): $corgiAudioManagementLib is missing. Exiting..."
+  echo "ERROR (corgi-audio-control): $corgiAudioManagementLib is missing. Exiting..."
+  exit 1
+fi
 
-          case "$line" in 
+export XAUTHORITY=/home/$USER/.Xauthority
 
-            *'[on]'*)
-              muteDirective='mute'
-              break
-            ;;
+. "$corgiAudioManagementLib"
 
-            *'[off]'*)
-              muteDirective='unmute'
-              break
-            ;;
-
-          esac
-
-        done
-
-        $audioHandler 'sset' 'Master' "$muteDirective"
-
-      }
-
-    ;;
-
-  esac
-
-}
-
-(corgiUpdateVolume "$@")
+setAudio "$@"
